### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by TuanTNG** [zju3dv/pats#2]
Hi, 
Thank you so much for your awesome work.
When will you release your code?

**Comment by xuanlanxingkongxia** [comment]
We will release our code at the end of June.
Thanks for your following.

**Comment by TuanTNG** [comment]
Hi @xuanlanxingkongxia,
Thank you for your reply.

By the way, I have a question related to inference speed. May you help to compare the inference speed of your model with LoFTR?

**Comment by xuanlanxingkongxia** [comment]
It takes about 1 second for pats to match a pair of image, which is 10 times of LoFTR, while it is much faster than COTR and comparable with PDCNet+

**Comment by TuanTNG** [comment]
Thank you,

I got it. 
Looking forward to seeing your code.

**Comment by xuanlanxingkongxia** [comment]
In detail for our time and space efficiency:
PATS (900ms) is slower than LoFTR (64ms) but comparable with PDC-Net+ (850ms) when processing 640×480 images. Besides, PATS (5.0GB) occupies more memory than LoFTR (3.6GB) but less memory than PDC-Net+(5.6GB). However, thanks to the scale-adaptive subdivision, for 1600×1200 images, PATS (8.3GB) consumes less memory than LoFTR (22GB) and PDC-Net+(23GB).

**Comment by xuanlanxingkongxia** [comment]
All of the tests are conducted on RTX 3090

**Comment by Master-cai** [comment]
@xuanlanxingkongxia hello, any update about the code release?

**Comment by eugenelyj** [comment]
Sorry for the delay. We have released the evaluation code and the pre-trained model. We are still working on the release of the training script, which is expected to appear at the end of this year.
