### ISSUE TITLE
this is a error

### ISSUE THREAD

**Issue by LooperzZ** [zju3dv/pats#5]
File "C:\Users\86132\Desktop\pats-master\utils\utils.py", line 17, in <module>
    import tensor_resize
ModuleNotFoundError: No module named 'tensor_resize'

**Comment by xuanlanxingkongxia** [comment]
Do you have run setup.py?

**Comment by eugenelyj** [comment]
@LooperzZ 
Please read the section of `Installation`.
You need to run
```
conda env create -f environment.yaml
cd setup
python setup.py install
cd ..
```

**Comment by eugenelyj** [comment]
Feel free to re-open the issue if you don't solve this problem.
