### ISSUE TITLE
Is it possible to set batch size as > 1?

### ISSUE THREAD

**Issue by GrayMask** [zju3dv/pats#6]

**Comment by GrayMask** [comment]
Thanks for your great work. It performs pretty well in my own dataset!
I want to know if it is possible to set batch size as a num > 1, (so that I can input multiple image pairs into model to save time)
I notice that the batch size is always set as 1 in your demo.

**Comment by xuanlanxingkongxia** [comment]
Yes， you can set batch size num >1, however, the coordinates of matches are set as one array, this part of code should be modified when use higher batch size.

**Comment by GrayMask** [comment]
I see. Thanks for your reply!
