### ISSUE TITLE
Q about resize

### ISSUE THREAD

**Issue by TwiceMao** [zju3dv/pats#7]
How can I get matching coordinates in the dimensions of the original image? I mean not resized.

**Comment by TwiceMao** [comment]
Or is it possible that when the height and width of the image meet certain conditions, the height and width of the image will remain unchanged after the image goes through the Resize_img operation in your code.

**Comment by TwiceMao** [comment]
Or, is it okay if I don’t do the resize in your code during data preprocessing? If not, what will happen?

**Comment by xuanlanxingkongxia** [comment]
Thank for your question.
Our method need the input data to meet these criterions:
1. the resolution of query image and target image should be the same
2. the resolution of images should be an integer multiple of 32
these criterions could be satisfiled by padding 0
