### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by gggxxl** [zju3dv/pats#9]
What a great work！we are planning to use your work as a baseline and will cite it. When will you share the training code or release more training details? Thank you sincerely!

**Comment by xuanlanxingkongxia** [comment]
Oh, thank you very much for your recognition of our work, however, our training code maybe too messy for you, we will try our best to reorganize it. This may take some time.........

**Comment by xuanlanxingkongxia** [comment]
Or do you have any direct questions to know? I can reply to you here.

**Comment by gggxxl** [comment]
Thank you for your timely reply! It would be very helpful if you could provide a link to the current training codes or send it to 1740788824@qq.com, even though they are not reorganized yet. It's OK if you have any concerns doing that and thank you as well.

**Comment by xuanlanxingkongxia** [comment]
We still can't accept giving you code that is too ugly. Let's do this. We will simply organize it within two weeks and come up with a preliminary acceptable version and send it to you.

**Comment by gggxxl** [comment]
That sounds good! Thank you very much~

**Comment by LooperzZ** [comment]
Thank you for your timely reply! It would be very helpful if you could provide a link to the current training codes or send it to [gt_2995330760@163.com](mailto:gt_2995330760@163.com), even though they are not reorganized yet. It's OK if you have any concerns doing that and thank you as well.
